queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=check multipleHosts [x86_64-linux]
      - check-success=check pre-commit-check [x86_64-linux]
      - check-success=check shell [x86_64-linux]
      - check-success=check simple [x86_64-linux]
      - check-success=devShell default [x86_64-linux]
      - check-success=package default [x86_64-linux]
      - check-success=package queued-build-hook [x86_64-linux]
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
