queue_rules:
  - name: default
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=check
      - check-success=check nixos-module-test [x86_64-linux]
      - check-success=check pre-commit-check [x86_64-linux]
      - check-success=check shell [x86_64-linux]
      - check-success=devShell default [x86_64-linux]
      - check-success=package default [x86_64-linux]
      - check-success=package queued-build-hook [x86_64-linux]
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
